name: SurvivalGames
version: ${project.version}.${BUILD_NUMBER}
main: org.mcsg.survivalgames.SurvivalGames
## Original Author ##
author: [Double0negative]
## Current Author ##
author: ThunderGemios10
description: Fully Automated Hunger Games Plugin!
depend: [WorldEdit]

commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]

